### ISSUE TITLE
Script MezzioInstaller\OptionalPackages::install handling the pre-install-cmd event terminated with an exception

### ISSUE THREAD

**Issue by Ahmard** [mezzio/mezzio#136]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.14.0

#### Summary
An exception is thrown while trying to create mezzio application.
Below is the thrown exception:

Script MezzioInstaller\OptionalPackages::install handling the pre-install-cmd event terminated with an exception
In OptionalPackages.php line 583:
                                                                                                                                        
  file_get_contents(PROJECT_PATH/phpunit.xml.dist): Failed to open stream: No such file or directory

#### Current behavior
Fresh installation failing

#### How to reproduce
Run project creation command:
`composer create-project mezzio/mezzio-skeleton test`

#### Expected behavior

Ability to create new project

**Comment by samsonasik** [comment]
Already reported at https://github.com/mezzio/mezzio-skeleton/issues/109

**Comment by Ocramius** [comment]
Closing as duplicate

**Comment by Ahmard** [comment]
Okay, thank you.
