### ISSUE TITLE
Upgrading to PHP 8.2 breaks Dependency Injection

### ISSUE THREAD

**Issue by kaktusas2598** [mezzio/mezzio#139]
### BC Break Report

Hello, I am trying to update our PHP Webapp from PHP 8.1 to 8.2 and so I had to Upgrade some package versions in composer.json, updated these packages:

Mezzio: From 3.3 to 3.15
Laminas Config: From 3.3 to 3.8
Laminas File from 2.11.0 to 2.12.0
Laminas Http From 2.7.0 to 2.15.0
Laminas Uri From 2.7.1 to 2.10.0
Laminas xmlrpc from 2.7 to 2.15

#### Summary

After upgrading packages app is not loading anymore and I get this:

```
DI\Definition\Exception\InvalidDefinition: Entry "Laminas\HttpHandlerRunner\RequestHandlerRunnerInterface" cannot be resolved: the class is not instantiable
Full definition:
Object (
class = #NOT INSTANTIABLE# Laminas\HttpHandlerRunner\RequestHandlerRunnerInterface
lazy = false
)

File: /srv/www/vendor/php-di/php-di/src/Definition/Exception/InvalidDefinition.php
```

#### Previous behavior

Previously on PHP 8.1 on the Mezzio version 3.3 app was working fine.
Also upgrading from PHP 8.0 to 8.1 caused no issues whatsoever.

#### Current behavior

Seems like currently DI is broken for some laminas packages

#### How to reproduce

Upgrade packages mentioned above

**Comment by Ocramius** [comment]
Does the 3.15 version work on PHP 8.0 and 8.1?

**Comment by froschdesign** [comment]
> Seems like currently DI is broken for some laminas packages

But this is [PHP-DI](https://github.com/PHP-DI/PHP-DI), not Mezzio or Laminas.

**Comment by froschdesign** [comment]
@Ocramius 
Is PHP-DI officially supported by Mezzio?

**Comment by kaktusas2598** [comment]
Just reverted back to PHP 8.1 and getting the same error, not sure about PHP-DI, it was always working up until this point and I'm not even sure this is a problem with PHP-DI itself

**Comment by froschdesign** [comment]
I found it: the integration of PHP-DI is done by [elie29/zend-di-config](https://github.com/elie29/zend-di-config)

**Comment by kaktusas2598** [comment]
@froschdesign We are not using this package, do you think this would help me? Is there any reason why we didn't need it before

**Comment by froschdesign** [comment]
> We are not using this package, do you think this would help me? Is there any reason why we didn't need it before

If you use the installer to create a application and choose PHP-DI as dependency injection container then [elie29/zend-di-config](https://github.com/elie29/zend-di-config) will be used to provide this support.
I don't know how you started/installed your application and how PHP-DI can be used with or without zend-di-config.

**Comment by kaktusas2598** [comment]
Ok, we finally got it working, all I had to do is open our di config for Mezzio and change this definition:
`RequestHandlerRunner::class`
to
`RequestHandlerRunnerInterface::class`.

Still not sure why it was working before though

**Comment by froschdesign** [comment]
@kaktusas2598 
Thanks for your feedback! 👍🏻
