### ISSUE TITLE
[RFC]: Remove Pimple from Mezzio documentation and from Mezzio skeleton

### ISSUE THREAD

**Issue by Xerkus** [mezzio/mezzio#145]
## RFC

| Q                   | A      |
| ------------------- | ------ |
| Proposed Version(s) | x.y.0  |
| BC Break?           | No |

### Goal

Pimple readme states
> Pimple is now closed for changes. No new features will be added and no cosmetic changes will be accepted either. The only accepted changes are compatibility with newer PHP versions and security issue fixes.

Pimple was not the most used container with mezzio to begin with. It was on life support for a while, going into maintenance only in 2020. I think it is time to let it go.

I propose to drop Pimple from Mezzio documentation and drop it from Mezzio skeleton installer.

**Comment by settermjd** [comment]
Happy to implement this, if there are no other takers.

**Comment by Xerkus** [comment]
@Ocramius  I do not think this needs new major as it does not introduce any changes to mezzio itself.

**Comment by froschdesign** [comment]
The related package [laminas-pimple-config](https://github.com/laminas/laminas-pimple-config) is already abandoned.

**Comment by gsteel** [comment]
Closed via #188
