### ISSUE TITLE
Tutorial - Getting start - suggestion

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio#15]
I've found "generate-factory-for-class" very usefull, but executing it on Windows was a small problem at first. 
If I could suggest a small change in this tutorial, I recomend adding a comment saying that correct syntax of this command would be:
.\vendor\bin\generate-factory-for-class "App\Action\TemplateTestAction" > src/App/src/Action/TemplateTestActionFactory.php

The biggest problem was that classname shouldn't be App\\\\Action\\\\TemplateTestAction but App\Action\TemplateTestAction. Well, at least in my environment.

---

Originally posted by @asui at https://github.com/zendframework/zend-expressive/issues/472

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
