### ISSUE TITLE
[RFC]: Remove Aura.Di from Mezzio documentation and from Mezzio skeleton

### ISSUE THREAD

**Issue by froschdesign** [mezzio/mezzio#173]
## RFC

| Q                   | A      |
| ------------------- | ------ |
| Proposed Version(s) | x.y.0  |
| BC Break?           | No |

### Goal

Aura.Di does not support PHP 8.2 and [laminas-auradi-config](https://github.com/laminas/laminas-auradi-config) is already abandoned. Therefore, Aura.Di should be removed from the Mezzio documentation and from the Mezzio skeleton installer.

**Comment by froschdesign** [comment]
Related to #145

**Comment by gsteel** [comment]
Closed via #188
