### ISSUE TITLE
Add docs for extension config parameter for zend view renderer

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio#2]
Provide a narrative description of what you are trying to accomplish:

2.2.0 release of `zendframework/zend-expressive-zendviewrenderer` adds support for `extension` parameter for default suffix to be used by zend-view resolver, in line with other template renderers.

- [x] Is this related to documentation?
  Add documentation entry for `extension` config parameter.

---

Originally posted by @Xerkus at https://github.com/zendframework/zend-expressive/pull/664

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
