### ISSUE TITLE
Update installer screenshot - mezzio instead of expressive

### ISSUE THREAD

**Issue by michalbundyra** [mezzio/mezzio#23]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | x.y.z

#### Summary

We need replace installer screenshot in the documentation to refer mezzio instead of expressive.
![](https://docs.mezzio.dev/mezzio/images/installer.png)

**Comment by heiglandreas** [comment]
Screenshot already exists. See https://github.com/mezzio/mezzio-skeleton/pull/8

**Comment by samsonasik** [comment]
should can be closed in favor of #8

**Comment by samsonasik** [comment]
I talked with @michalbundyra that it needs to be re-opened as it is about different place.

**Comment by gsteel** [comment]
Closed via #165
