### ISSUE TITLE
Cannot set error handler layout to null

### ISSUE THREAD

**Issue by bkilinc** [mezzio/mezzio#28]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | x.y.z

#### Current behavior

I will not use layout templates for error pages, so I want to set layout to null for error templates. Using this configuration;
[ 'mezzio' => [ 'error_handler' => [ 'layout' => null ] ] ]
this does not cancel layout. However, instead of null if I use empty string ('') this works. But I don't know if this is right and will break in future versions. 
This behaviour is inconsistent with other parts. For example I can cancel global layout with this configuration;
[ 'templates' => ['layout' => null] ]

#### How to reproduce

[ 'mezzio' => [ 'error_handler' => [ 'layout' => null ] ] ]
does not cancel error handler layout.

#### Expected behavior
[ 'mezzio' => [ 'error_handler' => [ 'layout' => null ] ] ]
should cancel error handler layout

**Comment by michalbundyra** [comment]
I can confirm, that there is inconsistency as you noted, as a reference, please see:

https://github.com/mezzio/mezzio/blob/a7232dfff9ca816671eb6de99098e9c2bb5495dd/src/Container/ErrorResponseGeneratorFactory.php#L28-L29

https://github.com/mezzio/mezzio/blob/a7232dfff9ca816671eb6de99098e9c2bb5495dd/src/Container/NotFoundHandlerFactory.php#L30-L31

https://github.com/mezzio/mezzio-laminasviewrenderer/blob/cbb5f65e368b556ae69fdf44dfa818f8630f84ec/src/LaminasViewRendererFactory.php#L85

Not sure yet, how we can resolve it. Looks like in error handlers we are expecting layout to be string, and cannot be null.

**Comment by weierophinney** [comment]
@michalbundyra Looking at those containers, I think we could change those statements to read:

```
$config = $config['mezzio']['error_handler'] ?? [];

$layout = array_key_exists('layout', $config) ? (string) $config['layout'] : SOME_CLASS_CONSTANT;
```

This would convert a `null` value to an empty string in those scenarios, which would give us the same result, and _should_ work with all available renderers.
