### ISSUE TITLE
Apache https configuration will produce 404 for all routes

### ISSUE THREAD

**Issue by antje-78** [mezzio/mezzio#42]
### Bug Report

I have a mezzio-project developed. I use the Apache Server. The problem is that my https-requests will produce 404-errors, but when i changed to http it will work.

**Comment by samsonasik** [comment]
getlaminas.org is using mezzio project as well, works ok with https https://getlaminas.org/ .

Seems may be related with your apache config. Please ask at https://discourse.laminas.dev/ instead for question.

**Comment by antje-78** [comment]
ok, thanks
