### ISSUE TITLE
development config symlink not deleted after installing as with --no-dev option

### ISSUE THREAD

**Issue by bkilinc** [mezzio/mezzio#45]
### Bug Report
after running 
composer install --no-dev
config/autload/development.local.php symlink still remains .
My project crashes with error message "Uncaught Error: Class 'Whoops\Run' ".
I have to manually delete "development.local.php" after install. 
May be there is a problem with my workflow. I sync development files to deployment space and run composer install --no-dev afterwards. But at least switching from development to no-dev should work. 

|    Q        |   A
|------------ | ------
| Version(s)  | x.y.z

#### Current behavior

composer install
composer install --no-dev
config/autload/development.local.php symlink still remains .

#### Expected behavior

composer install
composer install --no-dev
config/autload/development.local.php should not exist

**Comment by bkilinc** [comment]
sorry, I should use "composer development-disable"

**Comment by michalbundyra** [comment]
@bkilinc I think this is expected behaviour.

Please see: https://docs.mezzio.dev/mezzio/v3/getting-started/quick-start/#development-tools

So you need to disable development mode before running `composer install --no-dev`.
