### ISSUE TITLE
Switch to vimeo/psalm

### ISSUE THREAD

**Issue by michalbundyra** [mezzio/mezzio#47]
On our [last TSC meeting](https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-static-analysis-tooling) we agreed to use `vimeo/psalm` as a static analysis tool.

We'd like to switch to use this library instead of phpstan.

Example implementation and configuration can be found in:
- https://github.com/laminas/automatic-releases
- https://github.com/laminas/laminas-cli

**Comment by azjezz** [comment]
I'll take on this one if that's okay? :)
