### ISSUE TITLE
NotFoundHandler generateTemplatedResponse Content Type missing

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio#5]
I believe "Content-Type" header is missing from the newly created response object when a 404 error is handled.

/src/Handler/NotFoundHandler.php

```php
/**
     * Generates a response using a template.
     *
     * Template will receive the current request via the "request" variable.
     */
    private function generateTemplatedResponse(
        TemplateRendererInterface $renderer,
        ServerRequestInterface $request
    ) : ResponseInterface {

        $response = ($this->responseFactory)()->withStatus(StatusCodeInterface::STATUS_NOT_FOUND);
        $response->getBody()->write(
            $renderer->render($this->template, ['request' => $request, 'layout' => $this->layout])
        );

        return $response;
    }
```
Should be 
```php
/**
     * Generates a response using a template.
     *
     * Template will receive the current request via the "request" variable.
     */
    private function generateTemplatedResponse(
        TemplateRendererInterface $renderer,
        ServerRequestInterface $request
    ) : ResponseInterface {

        $response = ($this->responseFactory)()
                 ->withHeader('Content-Type', 'text/html')
                 ->withStatus(StatusCodeInterface::STATUS_NOT_FOUND);
        $response->getBody()->write(
            $renderer->render($this->template, ['request' => $request, 'layout' => $this->layout])
        );

        return $response;
    }
```

---

Originally posted by @cgaube at https://github.com/zendframework/zend-expressive/issues/647

**Comment by weierophinney** [comment]
Not 100% sure if this relates to your problem, but I get a server 500 error on anything "that goes wrong" in my application, even for 404's. - when I switch PHP error reporting off then all works... which is clearly a sign of bad architecture.
One would imagine that a framework with PSR-7 & 15 at its roots would have the basics of HTTP sorted, clearly not... 
I'm so tired of wasting time with Zend's convoluted configuration and over-engineered concepts, and code examples which are naive or simply does not work.... 
wish I could say, I'm done with Zend and going back to PHP Slim, but the previous developers made the mistake of choosing Zend Expressive and now we are stuck with this bad experience.... and reminds me of why ZF never became popular and why I left ZF1-2 years ago.

---

Originally posted by @TradeSharer at https://github.com/zendframework/zend-expressive/issues/647#issuecomment-465085224

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
