### ISSUE TITLE
Missing documents about building complex queries.

### ISSUE THREAD

**Issue by eguvenc** [mezzio/mezzio#53]
### Bug Report

Missing documents about building complex queries using like operators and others. Related topic https://discourse.laminas.dev/t/how-to-build-complex-queries-using-like-methods/1929/5

|    Q        |   A
|------------ | ------
| Version(s)  | x.y.z

#### Summary

Should added to documentation.

#### Current behavior

There is no detailed information.

#### How to reproduce

-

#### Expected behavior

https://discourse.laminas.dev/t/how-to-build-complex-queries-using-like-methods/1929/5

**Comment by froschdesign** [comment]
@eguvenc 
This topic is related to [laminas-db](https://docs.laminas.dev/laminas-db/) and has nothing to do with Mezzio. Please reopen the issue report in the related issue tracker: https://github.com/laminas/laminas-db/issues
