### ISSUE TITLE
Remove `--ignore-platform-reqs` flag from `.travis.yml` when dependencies are updated/ready for PHP 8

### ISSUE THREAD

**Issue by Ocramius** [mezzio/mezzio#62]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#60 introduces PHP 8 compatibility, but by adding a `--ignore-platform-reqs` composer flag during installation.

That's OK, since we're doing it to speed up the upgrade to PHP 8, but we need to remove said flag in `3.4.0`

**Comment by jensdenies** [comment]
Mezzio-aurarouter is the last dependency that needs PHP 8 support in order to remove the flag. I've opened a PR a little while ago to prepare for the upgrade (bumps PHPUnit to 9.3 and PHP to 7.3).

https://github.com/mezzio/mezzio-aurarouter/pull/3

**Comment by jensdenies** [comment]
It turns out we also need a PHP 8 compatible `laminas/laminas-psr7bridge` release. There's a PR still pending at: https://github.com/laminas/laminas-psr7bridge/pull/9.

**Comment by Ocramius** [comment]
@jensdenies released :+1:

**Comment by jensdenies** [comment]
@Ocramius Thanks! I will create a PR with the updated dependency later on this evening.

Edit: I can probably do it in #63.

**Comment by jensdenies** [comment]
@Ocramius I've created the PR at #64.

**Comment by lcobucci** [comment]
Handled by #64
