### ISSUE TITLE
Empty response with WhoopsErrorResponseGenerator and zend-expressive-swoole

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio#7]
I'm just playing around with expressive and zend-expressive-swoole and noticed that given the WhoopsErrorResponseGenerator is configured as ErrorResponseGenerator no response body will be sent. The default ErrorResponseGenerator however works fine. 

### Expected results

Get response body generated by WhoopsErrorResponseGenerator

### Actual results

empty response on errors. 

---

Originally posted by @iwyg at https://github.com/zendframework/zend-expressive/issues/635

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
