### ISSUE TITLE
isMap assertion is breaking the skeleton installation

### ISSUE THREAD

**Issue by internalsystemerror** [mezzio/mezzio#71]
Recently trying to work on a PR for `mezzio-skeleton` and I'm getting a lot of failing tests regarding config being an `ArrayObject` and not a map caused by the following line:

https://github.com/mezzio/mezzio/blob/af67e673959bbd60013fd777326117edf6288899/src/Container/ServerRequestErrorResponseGeneratorFactory.php#L24

I also found the following related issue: https://github.com/mezzio/mezzio-authentication/pull/11/files

**Comment by boesing** [comment]
Closed by #72
