### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by agustingomes** [mezzio/mezzio#95]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

This issue aims to track the PHP 8.1 support addition to the project. Happy to help on this issue if it's necessary.

**Comment by agustingomes** [comment]
@boesing what should be the base branch in this case, 3.6.x or 4.0.x?

**Comment by froschdesign** [comment]
@agustingomes 
The support of PHP 8.1 can be added in a minor version which means for this package: 3.7.0. The related branch is [3.7.x](https://github.com/mezzio/mezzio/tree/3.7.x).

**Comment by agustingomes** [comment]
perfect. I'll invest some time for this today

**Comment by agustingomes** [comment]
I've ran updates to the composer.lock of the project, and what I found so far in the PR:

- all the direct dependencies under `require` are ready for PHP 8.1
- all the following dev dependencies need to be upgraded to be compatible with PHP 8.1
  - `laminas/laminas-coding-standard` (upgrading to ^2.3 would make it compatible)
  - `mezzio/mezzio-aurarouter` https://github.com/mezzio/mezzio-aurarouter/issues/10
  - `mezzio/mezzio-laminasrouter` https://github.com/mezzio/mezzio-laminasrouter/issues/10
- with `E_ALL` set for `error_reporting` some test are failing, but that is tied to the point above.

**Comment by agustingomes** [comment]
@froschdesign I see some 7.3 tests fail. on e of the dependencies involved is `laminas/laminas-servicemanager` which is no longer compatible since 3.8.0, which is the same version that PHP 8.1 support was added for it.

Is this an indication we should drop PHP 7.3 as dependency?

**Comment by froschdesign** [comment]
@agustingomes 
See my comment on the pull request. 😉

**Comment by agustingomes** [comment]
I removed support for 7.3.

Additionally I updated the coding standards package to be compatible with 8.1, but one of the sniffs of the `2.3.0` can introduce breaking code for 7.4.

Here is the explanation i added in the commit:

> The exclusions added avoid breaking code to be added, since the sniff
targeted replaces occurrences of `get_class($instance)` by
`$instance::class` which is not compatible with PHP 7.4.

**Comment by agustingomes** [comment]
I'll work the next days on the other 2 issues I opened, before proceeding further with the PR for this repository.

**Comment by mrVrAlex** [comment]
What about support for laminas-httphandlerrunner 2.x versions? It is possible have support both 1.x && 2.x in composer?

**Comment by agustingomes** [comment]
@shandyDev I took a brief look, but it seems it's not possible easily, since supporting 2.x now will entail some degree of  refactoring, which I feel it's out of scope for PHP 8.1 support.

I would suggest to open a new issue, so the maintainers can assess if this request is feasible.

**Comment by mrVrAlex** [comment]
Agree. httphandlerrunner 1.x have PHP 8.1 support, this should be separate issue.

**Comment by agustingomes** [comment]
Closed with https://github.com/mezzio/mezzio/pull/96
